
name: static_demo

on: 
  workflow_dispatch:

jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.3

      - name: Setup Veracode
        run: |
         curl -fsS https://tools.veracode.com/veracode-cli/install | sh

      - name: Package App
        run: |
         ./veracode package -s . --output verascan -a

      - name: Validate artifact
        run: |
         mv ./verascan/veracode-auto-pack-verademo-go-go.zip ./verascan/artifact.zip
          
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.8
        with:
          appname: 'verademo-go'
          createprofile: true
          filepath: './verascan/artifact.zip'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          scantimeout: 360
#          createsandbox: 'true'
#          sandboxname: 'SANDBOXNAME'
#          exclude: '*.js'
#          include: '*.war'
#          criticality: 'VeryHigh'